num1=int(input("Enter a positive value: "))
num2=int(input("Enter another positive value: "))
import math
num3=math.fabs(num1)
num4=math.fabs(num2)
print("Minimum Value")
print(min(num1,num2))
print("")
print("Maximum Value")
print(max(num1,num2))
print("")
print("Exponential value")
print(num1,"to the power of", num2)
print(math.pow(num1,num2))
print("")
print("Square roots")
print("The square root of your first number is", math.sqrt(num3))
print("The square root of your second number is", math.sqrt(num4))

